### ISSUE TITLE
MAC Version: Arrow Keys for Movement, Player weapons

### ISSUE THREAD

**Issue by darasy** [Mostly-BS-Totally-BA/mostly-bs-totally-ba#141]
Hi, first I just want to say "Great Job" for the game so far. It's great. I am writing to request a feature for the option to have the arrow keys on macbook working as the keys "w,a,s,d" as I find it more comfortable to play. Also, the player should have weapons to pick up in some locations and decide what kind of weapon they want to use, where different weapons provide different level of impact and also specify how many times or how long they can use it.

**Comment by ArodyDel** [comment]
I like your thoughts on this. A unique view point I haven't thought of! We were talking internally about adding a bow to the player and allow the player to shoot range attacks. The only thing we fear is if we added a bow it would clearly be used more over the sword. Ways to balance it out are still in discussion. I appreciate your input!

**Comment by crw24** [comment]
feature added, closing request
