### ISSUE TITLE
Add Ranged Weapon

### ISSUE THREAD

**Issue by Samaslamatha** [Mostly-BS-Totally-BA/mostly-bs-totally-ba#142]
We've seen that the enemies can use ranged weapons. So why not give the player a ranged weapon in one of the later levels?

**Comment by ArodyDel** [comment]
We were talking internally about adding a bow to the player and allow the player to shoot range attacks. The only thing we fear is if we added a bow it would clearly be used more over the sword. Ways to balance it out are still in discussion. I appreciate your input!

**Comment by crw24** [comment]
closing, merged
