### ISSUE TITLE
[Bug]Character can move toward wall after certain point at stage 2

### ISSUE THREAD

**Issue by jaimeenahn** [Mostly-BS-Totally-BA/mostly-bs-totally-ba#143]
While clearing stage 2, Character can't move beyond wall before I pass certain point at stage 2
However, after I opened and passed the door marked, 
![iom2](https://user-images.githubusercontent.com/32367255/38899369-9d1ebae8-4265-11e8-94ba-d0d8abb0560a.JPG)

game is slow down, and there is lagging. Also, the character can move toward the wall.

![iomm1](https://user-images.githubusercontent.com/32367255/38899566-3b379ee8-4266-11e8-9dc1-d130f411d5ab.JPG)

I don't know it is because I made too many zombies. But, I think you should know about this

**Comment by ArodyDel** [comment]
Thanks for submitting this bug we will look into it.
