### ISSUE TITLE
Feature request - damage values or hit indicator

### ISSUE THREAD

**Issue by Monomancer** [Mostly-BS-Totally-BA/mostly-bs-totally-ba#146]
Some kind of indicator that would show whether or not I was hitting the monsters successfully.  The same could go for when you get hit.  I know the monsters flash red but flashing the edges of the screen, or some other indicator for when the player is hit, and when the player hits a monster, would be excellent.

**Comment by crw24** [comment]
Thank you for the input/request, we will consider this for our official release

**Comment by crw24** [comment]
repeat request
