### ISSUE TITLE
[FEATURE REQUEST] Add ranged weapons (crossbow, bow/arrow, etc.)

### ISSUE THREAD

**Issue by rdsandid** [Mostly-BS-Totally-BA/mostly-bs-totally-ba#158]
I think it would add a new dynamic to the game, especially since there are 'safe' spots from a lot of the monsters/enemies.  Adding ranged weapons would give users some good tactical options on how to approach each room.

**Comment by ArodyDel** [comment]
We have already had multiple request for this. We are currently working to add this to the game

**Comment by crw24** [comment]
repeat request
