### ISSUE TITLE
Boss Mechanic 

### ISSUE THREAD

**Issue by ArodyDel** [Mostly-BS-Totally-BA/mostly-bs-totally-ba#69]
Need help creating Mechanics of the Level 2 Boss. The Goal is to have the Boss summon Zombies that chase the player down. Should summon in a ring of 5 zombies around the Boss. 

There is a prefab for a zombie or choose to make your own. Mainly editing the level 2 Boss script. 

The zombies should chase the player and die to one hit. The boss will summon these zombies once the player is close and have a cooldown of 10 secs before he can do it again

**Comment by xingtongli** [comment]
Hi, I find that you guys have finished the script of lvl2 BOSS. What should I do for this issue?

**Comment by xingtongli** [comment]
I have finished the script, and I pulled a request. Do you want to see the code firstly? I can send you by email.

**Comment by ArodyDel** [comment]
I've checked the code. You got it to spawn 5 zombies which is good. What is left is spawning them in a ring around the boss. Right now its a straight line.

**Comment by xingtongli** [comment]
You mean the five zombies should spawn in five rings, and around the boss?

**Comment by ArodyDel** [comment]
no one ring that consist of 5 zombies

**Comment by ArodyDel** [comment]
![zomb](https://user-images.githubusercontent.com/11743195/38965200-524318ea-4349-11e8-915a-2dfb33042a2e.png)
like this

**Comment by xingtongli** [comment]
So, where the boss stand? The ring is too small to contain one zombie and you want the 5 zombies around the boss. I cannot image the positions of them...

**Comment by xingtongli** [comment]
Ok, got it. thanks.

**Comment by ArodyDel** [comment]
yea, as you can see in the picture the zombies are in a circle

**Comment by ArodyDel** [comment]
Hey I just need your UBIT name for the jury duty

**Comment by xingtongli** [comment]
It's xli228. Hope you satisfy my job. Thanks.

**Comment by xingtongli** [comment]
Hi, I need your ubit also. Thanks.

**Comment by ArodyDel** [comment]
its arodydel
