### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by aforthma** [Mostly-BS-Totally-BA/mostly-bs-totally-ba#76]
Goal: Make the volume control slider in the options menu control the volume on the computer the game is being run on.

Game Object Details:
This update will focus on the MENU_Main scene. Under Canvas and BG is the game object needed called ObjectsMenu. Currently this contains only some basic parts include a slider that is intended to adjust the sound volume on the computer.

Script Details:
This should me made in MainMenu.cs and GameManager.cs. A function can be made that connects to the slider in MainMenu. This should then call a function in the GameManger that updates the master control volume variable. This variable should be accessible to the public, but not editable except through the update function.

Extra:
Alternatively, if this slider could maintain the volume of the game only and not the whole computer. An extra step that could be made would be to produce both an additional slider, one for each volume. Preferably as an additional step, the sliders would be reproduced in the OptionsMenu that is in the PauseMenu. This PauseMenu can be edited in scene MAP_Level1 under the Canvas. A separate PauseMenu.cs script is used to manage this.

**Comment by mengchunhsieh** [comment]
Hey, I just finished the requirement. Which branch should I use ?

**Comment by crw24** [comment]
merged closing
